export const GET_ALL_POSTS_REQUEST = "GET_ALL_POSTS_REQUEST"
export const GET_ALL_POSTS_SUCCESS = "GET_ALL_POSTS_SUCCESS"
export const GET_ALL_POSTS_FAIL = "GET_ALL_POSTS_FAIL"

export const GET_SINGLE_POST_REQUEST = "GET_SINGLE_POST_REQUEST"
export const GET_SINGLE_POST_SUCCESS = "GET_SINGLE_POST_SUCCESS"
export const GET_SINGLE_POST_FAIL = "GET_SINGLE_POST_FAIL"

export const CREATE_COMMENT_REQUEST = "CREATE_COMMENT_REQUEST"
export const CREATE_COMMENT_SUCCESS = "CREATE_COMMENT_SUCCESS"
export const CREATE_COMMENT_FAIL = "CREATE_COMMENT_FAIL"