export const GET_ALL_POSTS_REQUEST = "GET_ALL_POSTS_REQUEST"
export const GET_ALL_POSTS_SUCCESS = "GET_ALL_POSTS_SUCCESS"
export const GET_ALL_POSTS_FAIL = "GET_ALL_POSTS_FAIL"

export const GET_SINGLE_POST_REQUEST = "GET_SINGLE_POST_REQUEST"
export const GET_SINGLE_POST_SUCCESS = "GET_SINGLE_POST_SUCCESS"
export const GET_SINGLE_POST_FAIL = "GET_SINGLE_POST_FAIL"